### ISSUE TITLE
Please add a button to oopen https://gitpod.io/workspace

### ISSUE THREAD

**Issue by thiswind** [jeromewu/gitpod-window#2]
Your Extension looks great! Thank you for your great work ^_^ Y

could you please add one button here to open gitpod workspace。Because I always re-use existing Gitpod container,  and if I start gitopod on github, It will create a new container, it's a waste of resource.

![image](https://user-images.githubusercontent.com/23764/77406061-06fbd480-6def-11ea-86cd-b435def5c382.png)

**Comment by thiswind** [comment]
[this commit](https://github.com/jeromewu/gitpod-window/commit/2134b81bc14cd37497e182e3466da5a24df2ee01) implemented this issue.

**Comment by jeromewu** [comment]
Added in v1.1.0
