### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by th3c0d3br34ker** [jeromewu/gitpod-window#3]
Hey! @jeromewu I really appreciate your work. Are you still working on this for enhancements? There are a few bugs like opening a new workspace in a new window, where actually it should open in the same window. I understand that this isn't the official gitpod extension... still any chances of you still working on it?

**Comment by jeromewu** [comment]
Yeah, I am still working on this one, can you provide more details about the bug?

**Comment by th3c0d3br34ker** [comment]
Sure, when the extension is clicked on any site, it opens [workspace](https://gitpod.io/workspaces/). Now, if i already have a workspace, I would like to open it. When I do that, by default the page opens on a newtab. However, it would make more sense to open in it the same window rather than opening in a new one. 
When clicked on a repository site, it makes a new workspace which is absolutely fine.

**Comment by jeromewu** [comment]
Hi @th3c0d3br34ker 

The enhancement you mentioned has been done in v1.2.0, feel free to upgrade and try. :smile:
